### ISSUE TITLE
Android update Hello World file

### ISSUE THREAD

**Issue by gaurigadkari** [WomenWhoCode/WWCodeMobile#100]
Update the Hello World file with your Github handle, name, and introduction.
This should be a fun way to setup the development environment make your your first commit to this repo!

**Comment by vuinguyen** [comment]
To claim this issue to work on it, please comment in this issue and tag @gaurigadkari or @renweview in the #open-source-and-personal-projects channel in the WWCodeMobile slack.

Before posting questions in the #open-source-and-personal-projects channel, please review the [slides](https://github.com/WomenWhoCode/WWCodeMobile/blob/main/coding-projects/resources/slides/contributing-to-open-source-projects.pdf) and [video recording](https://www.youtube.com/watch?v=3CDY1Ex6L1s) of the open source workflow workshop.

**Comment by ThanaReka** [comment]
Hello, this is Reka! Super excited to be working on this project.  I enjoy trying new recipes and have my own website where I post recipes I've tried. My Github handle is @ThanaReka.
