### ISSUE TITLE
iOS - UI - Beginner - Add navigation title to Settings View

### ISSUE THREAD

**Issue by clc80** [WomenWhoCode/WWCodeMobile#104]
Add the Settings Title to the top of the `SettingsView.swift file`

- Feel free to add some color to the text and play with some SF Symbols as well. 
- Delete the to-do comment when you are done. 
<img src = "https://github.com/WomenWhoCode/WWCodeMobile/assets/16246070/aff8f3c5-2757-44c8-b342-1c7782e3cdd7" width = "300">

**Comment by pelumy** [comment]
@clc80, @devanshimodha, I would like to start with this.

**Comment by pelumy** [comment]
@devanshimodha, @clc80, I can't see the viewModel file for the settings. Am I meant to create one myself?
