### ISSUE TITLE
iOS - UI - Beginner - Add Section Header Info and Feedback

### ISSUE THREAD

**Issue by clc80** [WomenWhoCode/WWCodeMobile#105]
Add a Section Header to the `SettingsView` titled Info and Feedback

- Feel free to add some color to the text and play with some SF Symbols as well. 
- Delete the to-do comment when you are done. 

**Use this as an example:** 
<img src = "https://github.com/WomenWhoCode/WWCodeMobile/assets/16246070/11d30cfc-0f04-4a95-a9b5-f8eb57172684" width = "300">

**Comment by jancy123** [comment]
@clc80 @devanshimodha Im interested!
