### ISSUE TITLE
iOS - UI - Beginner - Add a Section Header to the `SettingsView` titled Notifications

### ISSUE THREAD

**Issue by clc80** [WomenWhoCode/WWCodeMobile#106]
Add a Section Header to the `SettingsView` titled Notifications

- Feel free to add some color to the text and play with some SF Symbols as well. 
- Delete the to-do comment when you are done. 

**Use this as an example:** 
<img src = "https://github.com/WomenWhoCode/WWCodeMobile/assets/16246070/11d30cfc-0f04-4a95-a9b5-f8eb57172684" width = "300">

**Comment by lulu-cao** [comment]
@clc80 @devanshimodha Can I work on this one, please?
