### ISSUE TITLE
iOS - UI - Beginner - Add a Section Header to the `SettingsView` titled What's New

### ISSUE THREAD

**Issue by clc80** [WomenWhoCode/WWCodeMobile#107]
Add a Section Header to the `SettingsView` titled What's New

- Feel free to add some color to the text and play with some SF Symbols as well. 
- Delete the to-do comment when you are done. 

**Use this as an example:** 
<img src = "https://github.com/WomenWhoCode/WWCodeMobile/assets/16246070/11d30cfc-0f04-4a95-a9b5-f8eb57172684" width = "300">

**Comment by DevHarleyA** [comment]
Hello! I'd like to pick this one up :)
