### ISSUE TITLE
iOS - UI - Beginner - Add a Section Header to the `SettingsView` titled Appearance

### ISSUE THREAD

**Issue by clc80** [WomenWhoCode/WWCodeMobile#108]
Add a Section Header to the `SettingsView` titled Appearance

- Feel free to add some color to the text and play with some SF Symbols as well. 
- Delete the to-do comment when you are done. 

**Use this as an example:** 
<img src = "https://github.com/WomenWhoCode/WWCodeMobile/assets/16246070/11d30cfc-0f04-4a95-a9b5-f8eb57172684" width = "300">

**Comment by namaswic** [comment]
@clc80 @devanshimodha I can take this issue.
