### ISSUE TITLE
IOS  - UI - Beginner - Add privacy row to settings view

### ISSUE THREAD

**Issue by clc80** [WomenWhoCode/WWCodeMobile#110]
- Add a "Privacy Policy" row in `SettingsView.swift`. 
- It should have an icon of your choice, text, and chevron. 
- Delete the to-do comment when you are done. 

Use the image as inspiration, it does not have to look exactly like this. 
<img src = "https://github.com/WomenWhoCode/WWCodeMobile/assets/16246070/6d74cf53-7551-4a04-8117-3ef351cae4bb" width = "300">

**Comment by namaswic** [comment]
@clc80 @devanshimodha I would like to work on this issue. Thank you!
