### ISSUE TITLE
IOS - UI - Beginner - Add a Rate app row to settings 

### ISSUE THREAD

**Issue by clc80** [WomenWhoCode/WWCodeMobile#112]
- Add a "Rate app" row in `SettingsView.swift`. 
- It should have an icon of your choice, text, and an arrow pointing away, or something similar to indicate they will be navigating away from the app. 
- Delete the to-do comment when you are done. 

Use the image as inspiration, it does not have to look exactly like this. 
<img src = "https://github.com/WomenWhoCode/WWCodeMobile/assets/16246070/53d7f440-e20a-4461-8dd0-36697f6e381c" width = "300">

**Comment by SttApollo** [comment]
@clc80  could you please assign this to me?
