### ISSUE TITLE
IOS - UI - Beginner - Add a follow us on twitter row in the settings

### ISSUE THREAD

**Issue by clc80** [WomenWhoCode/WWCodeMobile#113]
- Add a "Follow us on Twitter" row in `SettingsView.swift`. 
- It should have an icon of your choice, text, and an arrow pointing away, or something similar to indicate they will be navigating away from the app. 
- Delete the to-do comment when you are done. 

Use the image as inspiration, it does not have to look exactly like this. 
<img src = "https://github.com/WomenWhoCode/WWCodeMobile/assets/16246070/53d7f440-e20a-4461-8dd0-36697f6e381c" width = "300">

**Comment by lulu-cao** [comment]
@devanshimodha @clc80 Can I take this one, please?
