### ISSUE TITLE
IOS- UI - beginner - Add a version number row to the settings

### ISSUE THREAD

**Issue by clc80** [WomenWhoCode/WWCodeMobile#114]
- Add a "version 1.0" row in `SettingsView.swift`. 
- It should have an icon of your choice, text, and  a chevron
- Delete the to-do comment when you are done. 

Use the image as inspiration, it does not have to look exactly like this. 
<img src = "https://github.com/WomenWhoCode/WWCodeMobile/assets/16246070/6d74cf53-7551-4a04-8117-3ef351cae4bb" width = "300">

**Comment by jancy123** [comment]
@clc80 @devanshimodha I would like to work on this issue. thank you!

**Comment by jancy123** [comment]
@clc80 @devanshimodha do we need this info twice? isn't having in footer sufficient https://github.com/WomenWhoCode/WWCodeMobile/issues/122

**Comment by clc80** [comment]
> @clc80 @devanshimodha do we need this info twice? isn't having in footer sufficient #122

If we actually do build out the whole settings. I was thinking this would be a description of all the changes per version number, where the footer is just he current version.

**Comment by jancy123** [comment]
@clc80  makes sense thanks!
