### ISSUE TITLE
IOS- UI - Beginner - Add App theme row to Setting

### ISSUE THREAD

**Issue by clc80** [WomenWhoCode/WWCodeMobile#116]
- Add an "App theme" row in `SettingsView.swift`. 
- It should have an icon of your choice, text, and a chevron
- Delete the to-do comment when you are done. 

Use the image as inspiration, it does not have to look exactly like this. 
<img src = "https://github.com/WomenWhoCode/WWCodeMobile/assets/16246070/6d74cf53-7551-4a04-8117-3ef351cae4bb" width = "300">

**Comment by pelumy** [comment]
@devanshimodha, @clc80 , Please, I will like to work on this.
