### ISSUE TITLE
IOS - UI- Beginner - Add a show badge row in settings 

### ISSUE THREAD

**Issue by clc80** [WomenWhoCode/WWCodeMobile#119]
- Add a "Show Badge" row in `SettingsView.swift`. 
- It should have an icon of your choice, text, and a toggle
- Delete the to-do comment when you are done. 

Use the image as inspiration, it does not have to look exactly like this. 
<img src = "https://github.com/WomenWhoCode/WWCodeMobile/assets/16246070/0a555db7-90da-47b6-b60a-ea48c09752b7" width = "300">

**Comment by lulu-cao** [comment]
@clc80 @devanshimodha Can I take this one, please?
