### ISSUE TITLE
IOS - UI - slightly newer Beginner - Show Days Text In Settings

### ISSUE THREAD

**Issue by clc80** [WomenWhoCode/WWCodeMobile#120]
- Add the "Show Days" text in `SettingsView.swift`. 
- It should have and days of the week in a circle, which can be icons (SF symbols) or text. 
- Delete the to-do comment when you are done. 

Use the image as inspiration, it does not have to look exactly like this. 
<img src = "https://github.com/WomenWhoCode/WWCodeMobile/assets/16246070/0a555db7-90da-47b6-b60a-ea48c09752b7" width = "300">

**Comment by cyndichin** [comment]
thanks @clc80! I would like to work on this as my first issue.

**Comment by clc80** [comment]
> thanks @clc80! I would like to work on this as my first issue.

Great! Let us know if you have any questions or if you are ready for us to take a look at it.
