### ISSUE TITLE
IOS - UI - Beginner - Add Reminder Time row in Settings

### ISSUE THREAD

**Issue by clc80** [WomenWhoCode/WWCodeMobile#121]
- Add the "Reminder Time" row in `SettingsView.swift`. 
- It should have text on both sides of the row. 
- Delete the to-do comment when you are done. 

Use the image as inspiration, it does not have to look exactly like this. 
<img src = "https://github.com/WomenWhoCode/WWCodeMobile/assets/16246070/0a555db7-90da-47b6-b60a-ea48c09752b7" width = "300">

**Comment by jancy123** [comment]
@clc80 I am interested to work on this

**Comment by clc80** [comment]
> @clc80 I am interested to work on this

Let us know if you have any questions, or if you are done and you need us to take a look at it.
