### ISSUE TITLE
IOS - UI - Beginner - Add a version number footer to the section

### ISSUE THREAD

**Issue by clc80** [WomenWhoCode/WWCodeMobile#122]
- Add a "1.0 version number" in `SettingsView.swift`. 
- Feel free to change the color and add some sf symbols if you like. 
- Delete the to-do comment when you are done. 

Use the image as inspiration, it does not have to look exactly like this. 
<img src = "https://github.com/WomenWhoCode/WWCodeMobile/assets/16246070/53d7f440-e20a-4461-8dd0-36697f6e381c" width = "300">

**Comment by jancy123** [comment]
I would like to pick this @clc80 @devanshimodha

**Comment by devanshimodha** [comment]
Closing this as it is a duplicate for #114

**Comment by jancy123** [comment]
@devanshimodha @clc80 I can take this.

**Comment by clc80** [comment]
@jancy123 have you been able to make any progress on this issue?
