### ISSUE TITLE
iOS - UI - List Screen: Scaffold initial screen with headers, + button, and list container

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#124]
- Create a list screen
- Add headers
- Add + button
- Add container for list items

<img width="458" alt="Screenshot 2024-01-24 at 5 03 11 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/f49b0ff9-cacb-47d1-9ce4-8bda07afef2b">

**Comment by pelumy** [comment]
@devanshimodha , @clc80, I would love to work on this please.
