### ISSUE TITLE
iOS - UI - List Screen: Add list items that show activity name and time of activity

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#125]
- Add list items
- Display activity name for each item
- Display time duration of activity for each item
- List should scroll

<img width="458" alt="Screenshot 2024-01-24 at 5 03 11 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/0a43e2d8-aa8e-4e58-931d-5af5525b39e1">

**Comment by cyndichin** [comment]
@ceceliacreates I would like to work on this issue when it becomes unblocked.
