### ISSUE TITLE
iOS - UI - List Screen: Display list items in sections based on date

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#126]
- Add sections to displayed list items with date name header
- Display list items in sections based on date of item

<img width="458" alt="Screenshot 2024-01-24 at 5 03 11 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/5a69da59-7884-4811-b979-5f58e87fdb09">

**Comment by SttApollo** [comment]
I would like to work on this once this becomes unblocked.

**Comment by clc80** [comment]
@SttApollo This issue can now be worked on.
