### ISSUE TITLE
iOS - UI - List Screen: Link + button to Detail/Add/Edit screen

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#127]
Blocked by #124 

Link + button to Detail/Add/Edit screen

<img width="458" alt="Screenshot 2024-01-24 at 5 03 11 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/76808f99-c5a6-4bc0-9376-96f845f454fa">

**Comment by pelumy** [comment]
@clc80, @devanshimodha, I would love to work on this.
