### ISSUE TITLE
iOS - UI - Detail Screen: Scaffold initial screen with elements

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#128]
- Create Detail/Add/Edit screen
- Add Date, Start time, and End time text
- Add textbox for activity description
- Add button that displays date
- Add button that displays start time
- Add button that displays end time
- Add delete button
- Add cancel button
- Add done button

<img width="273" alt="Screenshot 2024-01-24 at 5 30 44 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/56d8fd68-1f15-4fa6-8d23-d5a73afb30ba">

**Comment by DevHarleyA** [comment]
I would like to pick this ticket up

**Comment by pelumy** [comment]
> I would like to pick this ticket up

@DevHarleyA , you will get a faster response if you tag the maintainers.
