### ISSUE TITLE
iOS - UI - Detail Screen: Add date picker

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#129]
- on tap of date button, launch date picker popup
- add date picker with cancel and ok options
- on tap of ok option, dismiss popup and display selected date on button
- on tap of cancel option, dismiss popup

<img width="727" alt="Screenshot 2024-01-24 at 5 40 51 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/63e79ac1-9c4c-46d8-99c1-2b0980f46d6d">

**Comment by jancy123** [comment]
@clc80 @devanshimodha I would like to work on this issue when it becomes unblocked. thank you!

**Comment by clc80** [comment]
> [@clc80](https://github.com/clc80) [@devanshimodha](https://github.com/devanshimodha) I would like to work on this issue when it becomes unblocked. thank you!

I am going to assign you to this task, just so that it doesn't get lost and I forget. And once it becomes unblocked please feel free to start working on it.

**Comment by clc80** [comment]
@jancy123 This issue can now be worked on.
