### ISSUE TITLE
iOS - UI - Detail Screen: Add confirmation popup for cancel button

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#131]
- on tap of cancel button, launch confirmation popup with ok and cancel options
- on tap of cancel option on popup, dismiss popup
- on tap of ok option, redirect back to List Screen

<img width="545" alt="Screenshot 2024-01-24 at 5 46 00 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/48cafa8e-dc3c-471d-b5e7-63d4173c06ab">

**Comment by DevHarleyA** [comment]
Hi @clc80 &  @devanshimodha, I would like to pick this ticket up next
#128 has been merged

**Comment by clc80** [comment]
@DevHarleyA This issue can now be worked on.

**Comment by DevHarleyA** [comment]
Good morning, I would like some extra time to work on this. My goal is to have a PR up by tomorrow (Friday Feb. 16) night.
