### ISSUE TITLE
iOS - UI - Detail Screen: Add confirmation popup for delete button

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#132]
- on tap of delete button, launch confirmation popup with ok and cancel options
- on tap of cancel option on popup, dismiss popup
- on tap of ok option, redirect back to List Screen

<img width="545" alt="Screenshot 2024-01-24 at 5 46 08 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/452c7b36-e729-448d-a5a1-30faddbc3cdb">

**Comment by pelumy** [comment]
@clc80 and @devanshimodha, I would like to work on this.

**Comment by ceceliacreates** [comment]
Hi @pelumy you have been assigned!
