### ISSUE TITLE
iOS - UI - Detail Screen: Done button redirect

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#133]
- On tap of Done button, redirect to List Screen

<img width="273" alt="Screenshot 2024-01-24 at 5 30 44 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/7bc3702a-9013-475a-b28b-434feb4ef85a">

**Comment by namaswic** [comment]
@clc80 @devanshimodha I can take this issue.
