### ISSUE TITLE
iOS - UI - Detail Screen: Only show delete icon when adding or editing item

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#134]
- Hide delete button when adding a new entry
- Display delete button when viewing details/editing an existing entry

<img width="273" alt="Screenshot 2024-01-24 at 5 30 44 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/fe7de29e-7d89-47a5-b91f-ca00a903bed4">

**Comment by jancy123** [comment]
I can work on this @clc80 @devanshimodha

**Comment by jancy123** [comment]
@devanshimodha @clc80 pls assign to me.
