### ISSUE TITLE
Android - Complete Usage section

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#135]
Complete the Usage section in the Android project README at `coding-projects/android/README.md`

**Comment by CBID2** [comment]
I'll work on this @ceceliacreates

**Comment by ceceliacreates** [comment]
@CBID2 There is a `TODO` in the file at `coding-projects/android/README.md` for the Usage section. This was originally intended for the maintainers, which is why there aren't many details. However, I would recommend adding:

- A brief overview of how the app is used
- A description of the usage flows of the app (Add Flow, Detail/Edit Flow, and Delete Flow)

I recommend referencing the slides from the Kickoff event that were posted in Slack. I'll tag you there so you can find them and will assign this issue to you!

**Comment by CBID2** [comment]
> @CBID2 There is a `TODO` in the file at `coding-projects/android/README.md` for the Usage section. This was originally intended for the maintainers, which is why there aren't many details. However, I would recommend adding:
> 
> 
> 
> - A brief overview of how the app is used
> 
> - A description of the usage flows of the app (Add Flow, Detail/Edit Flow, and Delete Flow)
> 
> 
> 
> I recommend referencing the slides from the Kickoff event that were posted in Slack. I'll tag you there so you can find them and will assign this issue to you!

Ahh I see
