### ISSUE TITLE
Algorithm-Club - Invalid characters in file name (for Windows)

### ISSUE THREAD

**Issue by jyoshna-joshi** [WomenWhoCode/WWCodeMobile#139]
Bug found while cloning the project in Windows. There were special characters in certain filenames.

> error: invalid path 'algorithm-club/April: Stacks&Queue.md'
> error: invalid path 'algorithm-club/February: Arrays&Strings.md'
> error: invalid path 'algorithm-club/January: Complexity&Basics.md'
> error: invalid path 'algorithm-club/March: LinkedList.md'

To solve this issue, special characters such as ":", " ", "&" can be removed.

**Comment by vuinguyen** [comment]
This file is not part of the Android or iOS coding projects though, so this is not code that needs to be fixed. You will need to go to the coding-projects folder/android for the Android Project. I will close your issue.

**Comment by jyoshna-joshi** [comment]
Since I need to clone whole repository for getting access to 'coding-projects/android' folder, issue with 'algorithm-club' will need to be fixed before I can clone it.

**Comment by ceceliacreates** [comment]
This is related to cloning the project locally on a Windows OS. There are certain special characters that Windows does not allow in filenames. The list of reserved characters is here: https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

In this case, I believe the & is the issue and would need to be removed from these file names.

This is a potential workaround in the meantime: https://confluence.atlassian.com/bitbucketserverkb/error-invalid-path-during-git-clone-to-windows-client-1085186345.html

**Comment by renweview** [comment]
Assigned myself on this issue, working on this now. Encountered the same problem on my Windows PC.

**Comment by ceceliacreates** [comment]
@renweview Were you able to update this? If not I can submit a quick PR that changes the file names.

**Comment by renweview** [comment]
https://github.com/WomenWhoCode/WWCodeMobile/pull/201 given this was successful, @jyoshna-joshi does forking the repo directly now work on your pc? If so we can close

**Comment by jyoshna-joshi** [comment]
I will check and let you know.

**Comment by jyoshna-joshi** [comment]
Yes, now it works. We can close this issue.
