### ISSUE TITLE
Android - Create a PR template

### ISSUE THREAD

**Issue by baghaii** [WomenWhoCode/WWCodeMobile#140]
Create a Pull Request template that includes the issue number and a description of the changes that have been made.

Information on how to do this: [Creating a pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

**Comment by vuinguyen** [comment]
That #143 PR didn't quite fix it, so I had to work on #144 to get it done.

**Comment by vuinguyen** [comment]
Did a quick test by trying to create a new PR and the PR template popped up! So will call this issue closed
