### ISSUE TITLE
Change NavigationView to a NavigationStack in SettingsView.swift

### ISSUE THREAD

**Issue by clc80** [WomenWhoCode/WWCodeMobile#148]
To stay up to date with future Apple changes let's get our code updated by upgrading the NavigationView to use NavigationStack

**Comment by namaswic** [comment]
Hi @clc80 & @devanshimodha, I would like to pick this ticket up next

**Comment by clc80** [comment]
@namaswic have you been able to make any progress on this issue?

**Comment by namaswic** [comment]
@clc80 Hey Claudia, Sorry, I completely forgot about picking this task. I can likely get to it in the next 3 days. Hope that is ok.
