### ISSUE TITLE
Android - UI - Beginner - Add a section header for Info & Feedback

### ISSUE THREAD

**Issue by baghaii** [WomenWhoCode/WWCodeMobile#156]
Add a section header for Info & Feedback. Play with size, color, and style. 

<img src = https://github.com/WomenWhoCode/WWCodeMobile/assets/7873908/bdea9814-fdd5-49ed-83f9-d6182df5db38 width="400">

**Comment by jyoshna-joshi** [comment]
Hi, Can I work in this section once it is available?

**Comment by jyoshna-joshi** [comment]
@renweview @gaurigadkari
