### ISSUE TITLE
Android - UI - Beginner - Add a Notifications Header

### ISSUE THREAD

**Issue by baghaii** [WomenWhoCode/WWCodeMobile#167]
In the `TaskSettingsScreen`, add a section header for "Notifications." Play with font styles and sizes of the Text composable. Remove the TODO when you are done.

<img src = https://github.com/WomenWhoCode/WWCodeMobile/assets/7873908/206b68e2-0f65-4e93-9aa8-bad6cf7162f7 width=400>

**Comment by XenaWarrio** [comment]
@baghaii can I take this?

**Comment by renweview** [comment]
@XenaWarrio i think youre assigned https://github.com/WomenWhoCode/WWCodeMobile/issues/168 we can only assign one at a time

**Comment by XenaWarrio** [comment]
I'm ready to take this
