### ISSUE TITLE
Android - UI - Beginner - What's New?

### ISSUE THREAD

**Issue by baghaii** [WomenWhoCode/WWCodeMobile#168]
In the `TaskSettingsScreen`, add a section header for "What's New?" Play with font styles and sizes of the Text composable. Remove the TODO when you are done.

<img src = https://github.com/WomenWhoCode/WWCodeMobile/assets/7873908/206b68e2-0f65-4e93-9aa8-bad6cf7162f7 width=400>

**Comment by baghaii** [comment]
Yes, I have assigned this to you.

**Comment by XenaWarrio** [comment]
[pr](https://github.com/WomenWhoCode/WWCodeMobile/pull/249) for this
