### ISSUE TITLE
Android - UI - Beginner - Add an App Icon Row

### ISSUE THREAD

**Issue by baghaii** [WomenWhoCode/WWCodeMobile#170]
- Add an "App Icon" row to the Appearance section of the`TaskSettingsScreen.kt` with an icon and a text.
- Move your text to the `string.xml` file and use a `stringResource` with your resource id to fetch your string from `strings.xml` (There is an example of this in `TaskListscreen.kt`) 
- Remove the TODO for issue 166 in the file when you are done.

<img src=https://github.com/WomenWhoCode/WWCodeMobile/assets/7873908/0be8ebf4-4d96-4c7a-a604-04675c49f05a width=400>

**Comment by Shradhajoshi** [comment]
Hi, @baghaii @renweview I would like to work on this.

**Comment by renweview** [comment]
@Shradhajoshi since you're assigned https://github.com/WomenWhoCode/WWCodeMobile/issues/174 we can only assign one at a time
