### ISSUE TITLE
Android - UI - Beginner - Add an App Theme row

### ISSUE THREAD

**Issue by baghaii** [WomenWhoCode/WWCodeMobile#171]
- Add an "App Theme" row to the Appearance section of the`TaskSettingsScreen.kt` with an icon and a text.
- Move your text to the `string.xml` file and use a `stringResource` with your resource id to fetch your string from `strings.xml` (There is an example of this in `TaskListScreen.kt`) 
- Remove the TODO for issue 166 in the file when you are done.

<img src=https://github.com/WomenWhoCode/WWCodeMobile/assets/7873908/0be8ebf4-4d96-4c7a-a604-04675c49f05a width=400>

**Comment by cyndichin** [comment]
@renweview @gaurigadkari I would like to work on this issue if it's available. Thank you!

**Comment by renweview** [comment]
You got it @cyndichin

**Comment by renweview** [comment]
@cyndichin how's it going on this?

**Comment by cyndichin** [comment]
hi @renweview, I opened my PR. I wanted to wait until someone else contributed to one of the beginner issues first, but here's my attempt! thank you!
