### ISSUE TITLE
Android - UI - Beginner - Vote on Future Requests Row

### ISSUE THREAD

**Issue by baghaii** [WomenWhoCode/WWCodeMobile#172]
- Add a "Vote on Future Requests" row to the "What's New?" section of the`TaskSettingsScreen.kt` with an icon and a text.
- Move your text to the `string.xml` file and use a `stringResource` with your resource id to fetch your string from `strings.xml` (There is an example of this in `TaskListscreen.kt`) 
- Remove the TODO for issue 166 in the file when you are done.

<img src=https://github.com/WomenWhoCode/WWCodeMobile/assets/7873908/0be8ebf4-4d96-4c7a-a604-04675c49f05a width=400>

**Comment by XenaWarrio** [comment]
@vuinguyen @mgorkani 
Can I take this one?

**Comment by vuinguyen** [comment]
@XenaWarrio , you need to tag @renweview @baghaii @gaurigadkari if you'd like to be assigned to an issue, as they are the Android project maintainers

**Comment by XenaWarrio** [comment]
> @XenaWarrio , you need to tag @renweview @baghaii @gaurigadkari if you'd like to be assigned to an issue, as they are the Android project maintainers

sorry for that!

**Comment by vuinguyen** [comment]
No worries, @XenaWarrio ! I was just trying to provide you with some guidance so you can be assigned to an issue faster. Sorry if my last comment sounded a bit harsh. :)
