### ISSUE TITLE
Android - UI - Show Days

### ISSUE THREAD

**Issue by baghaii** [WomenWhoCode/WWCodeMobile#173]
- Add the "Show Days" text in `TaskSettings.kt`
- It should have and days of the week in a circle, which can be icons (SF symbols) or text.
- Delete the to-do comment when you are done.

<img src = https://github.com/WomenWhoCode/WWCodeMobile/assets/7873908/482762cd-85fc-46f0-abba-3cc2b04e3622 width=400>

**Comment by ThanaReka** [comment]
Hi @renweview @gaurigadkari, can I work on this issue once it becomes available?

**Comment by renweview** [comment]
@ThanaReka since you're assigned #93 I'll open this one up to users, feel free to ping if your PR for 93 is submitted soon

**Comment by ThanaReka** [comment]
Hi @renweview @gaurigadkari!  I've submitted my PR for 93 and would be happy to work on this issue now if it's still available.

**Comment by renweview** [comment]
@ThanaReka could you link your pr for 93?

**Comment by ThanaReka** [comment]
Sure. My PR handling issue #93 is #238.

**Comment by ThanaReka** [comment]
Hi @renweview @baghaii @gaurigadkari.  Still waiting to be assigned this issue so that I can submit a PR for it, before moving on to something else.  Thanks!

**Comment by renweview** [comment]
@ThanaReka thank you, you are assigned to this issue!
