### ISSUE TITLE
Android - UI - Beginner - Task Reminder Row

### ISSUE THREAD

**Issue by baghaii** [WomenWhoCode/WWCodeMobile#174]
- Add the "Task Reminder" text in `TaskSettingsScreen.kt`
- It should have a text, an icon, and a toggle button.
- Delete the to-do comment when you are done.

<img src = https://github.com/WomenWhoCode/WWCodeMobile/assets/7873908/482762cd-85fc-46f0-abba-3cc2b04e3622 width=400>

**Comment by Shradhajoshi** [comment]
Hi, @baghaii @renweview I would like to work on this.
