### ISSUE TITLE
Android - UI - Beginner - Show Badge

### ISSUE THREAD

**Issue by baghaii** [WomenWhoCode/WWCodeMobile#175]
- Add the "Show Badge" text in `TaskSettingsScreen.kt`
- It should have a text, an icon, and a toggle button.
- Delete the to-do comment when you are done.

<img src = https://github.com/WomenWhoCode/WWCodeMobile/assets/7873908/482762cd-85fc-46f0-abba-3cc2b04e3622 width=400>

**Comment by Shradhajoshi** [comment]
Hi, @baghaii @renweview I would like to work on this.

**Comment by renweview** [comment]
@Shradhajoshi can't assign multiple issues, please let me know if you preferred one specifically

**Comment by Himanshu-Vishwas** [comment]
Is this issue still exists? I would like to work on this.

**Comment by baghaii** [comment]
I have assigned it to you, @Himanshu-Vishwas

**Comment by vuinguyen** [comment]
@renweview I noticed you closed the PR for this issue. So I unassigned the previous person so someone else can sign up for this issue
