### ISSUE TITLE
Android - UI - Beginner - Notification Time

### ISSUE THREAD

**Issue by baghaii** [WomenWhoCode/WWCodeMobile#176]
- Add the "Reminder Time" text in `TaskSettingsScreen.kt`
- It should have text on both sides of the row.
- Delete the to-do comment when you are done.

<img src = https://github.com/WomenWhoCode/WWCodeMobile/assets/7873908/482762cd-85fc-46f0-abba-3cc2b04e3622 width=400>

**Comment by Shradhajoshi** [comment]
Hi, @baghaii @renweview I would like to work on this.
