### ISSUE TITLE
Android - Integration - Add Timed Activity

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#186]
Integrate the logic created by #73 and the UI created by #84 and #69

Blocked until all issues complete.

**Comment by SttApollo** [comment]
I think this PR should address this. https://github.com/WomenWhoCode/WWCodeMobile/pull/270

**Comment by vuinguyen** [comment]
It looks all the issues referenced in this integration issue have been completed. Will close this now
