### ISSUE TITLE
iOS - Integration - Delete Timed Activity

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#192]
~Integrate the logic from #80 and the UI from #70~

Blocked until both issues completed.

**Comment by clc80** [comment]
@ceceliacreates I am trying to understand what this issue is for. Is there work that has to be done with it? The delete feature is pretty much complete. I just need to confirm it removes the item from persistence once the persistence is finalized.

**Comment by vuinguyen** [comment]
@clc80 based on the testing I've done, it seems like the Delete Timed Activity works now. We probably don't need this issue anymore.

@ceceliacreates Can we close this issue now?

**Comment by vuinguyen** [comment]
@clc80 @ceceliacreates I will go ahead and close this issue, since it looks like it is done, if that's alright. Closing it will hopefully avoid the confusion of someone wanting to work on this issue if it's not needed
