### ISSUE TITLE
Query SwiftData in List

### ISSUE THREAD

**Issue by clc80** [WomenWhoCode/WWCodeMobile#197]
1.  Query SwiftData in List and show any data. 

This tutorial can be followed - https://www.hackingwithswift.com/quick-start/swiftdata/querying-swiftdata-objects-in-swiftui Or you can find your own.

**Comment by pelumy** [comment]
@clc80 and @devanshimodha, I can work on this after it is unblocked

**Comment by clc80** [comment]
@pelumy this issue is available to be worked on, it's no longer blocked.
