### ISSUE TITLE
iOS - Logic (Bug) - Editing List Item Creates New List Item Instead

### ISSUE THREAD

**Issue by vuinguyen** [WomenWhoCode/WWCodeMobile#235]
There is a bug in the Editing function. When editing a list item, instead of updating the list item, a new list item is created instead.

In this video, I tapped on a row, modified the end time and pressed "Done". Upon returning to the list screen, a new row was created instead of the edited row being updated.

What needs to be fixed:
When we edit a row or list item, we should return to the list and see that the row we just edited has been updated, instead of seeing a new row added.

https://github.com/WomenWhoCode/WWCodeMobile/assets/1022275/653e214c-08c5-415d-86dc-8b9ebdc40cd9

**Comment by pelumy** [comment]
@clc80, @devanshimodha, I would love to work on this
