### ISSUE TITLE
iOS - UI - Add delete swiper for task

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#239]
In the Task List Screen, add functionality to Delete a task by swiping left on a single task in the list.

Example:

![swipetodeleteexample](https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/91056c3c-5f8e-46c4-a51a-c859c8ecee6a)

**Comment by vuinguyen** [comment]
There is a `DeleteConfirmationPopupView` already in the project that should be re-used when the user taps on the `Delete` button, to confirm that they want to delete the entry

**Comment by clc80** [comment]
@tsablon I didn't see that there was done in the delete wire frames. Is there another issue you would like to work with or if you wanted to keep doing work with wire frames I have some other features that you can work on.  Let me know on slack. You can send me a message there and we can talk about it .

**Comment by vuinguyen** [comment]
I'm going to re-open this issue since it is connected to a [PR](https://github.com/WomenWhoCode/WWCodeMobile/pull/259) that is still open and in need of review.
