### ISSUE TITLE
iOS - UI - Assign a priority to a task

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#240]
Add functionality to the app that lets a user mark a task with a priority of low, medium, or high.

- On the Detail/Add/Edit Screen, add a "Priority" field with select options of "Low", "Medium", or "High"
- On save, capture the Priority field value with the added or edited task
- If there is an existing priority value when editing a task, display that value as selected on initial edit

Blocked by #241

**Comment by cyndichin** [comment]
@clc80 and @devanshimodha, I would like to work on this issue, thank you!
