### ISSUE TITLE
iOS - Wireframe - Assign a priority to a task

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#241]
Create the wireframe for #240

**Comment by cyndichin** [comment]
@clc80 @devanshimodha I would like to work on this!

**Comment by cyndichin** [comment]
Here are the wireframes:
| Details Screen | List Screen | 
| --- | --- |
| ![image](https://github.com/WomenWhoCode/WWCodeMobile/assets/6743397/77192c35-90c9-4364-9937-976ec78ad798) | ![image](https://github.com/WomenWhoCode/WWCodeMobile/assets/6743397/c2575d37-28cc-4864-bd7d-20979954da27) |

Would I be able to work on the code portion as well?

**Comment by vuinguyen** [comment]
@cyndichin I would recommend you tag @clc80 and @devanshimodha when you are ready for a review for a faster response 😊

As for issue #240 , I would recommend commenting in that issue and tagging @clc80 and @devanshimodha to request assignment on that issue as well

**Comment by clc80** [comment]
I am going to mark this issue as closed as the wireframes are done
