### ISSUE TITLE
iOS - UI - Add comments section for task

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#242]
Add functionality to the app that lets a user add comments to a task.

- On the Detail/Add/Edit Screen, add a textbox field with the title "Comments"
- On save, capture the Comments field value with the added or edited task
- If there is an existing Comment value when editing a task, display that value in the textbox on initial edit

**Comment by DevHarleyA** [comment]
I would like to pick this ticket up

**Comment by DevHarleyA** [comment]
Good Morning, sorry for the delay. I intend to work on this issue this evening.

**Comment by clc80** [comment]
![Image](https://github.com/WomenWhoCode/WWCodeMobile/assets/16246070/35ae175c-f435-4f3d-9131-38baaa6ae6c4)

@DevHarleyA Here are the wireframes for this issue.
