### ISSUE TITLE
iOS - Wireframe - Add comments section for task

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#243]
Create wireframe for #242

**Comment by jancy123** [comment]
I am intersted to try @ceceliacreates

**Comment by vuinguyen** [comment]
@jancy123 it may be faster for you to tag @clc80 and @devanshimodha to request assignment on this issue 😊

**Comment by jancy123** [comment]
<img width="202" alt="Screenshot 2024-03-17 at 10 14 11 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/13859276/5789a846-0e5f-4916-9a19-9c34454c9917">

Please review @ceceliacreates @clc80 @devanshimodha

**Comment by clc80** [comment]
Great job.
