### ISSUE TITLE
iOS - Wireframes - Mark a task as done

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#245]
Create wireframes for updated screens for #244 

- Update Details/Add/Edit Screen with "Done" button
- New "Done Tasks" screen

**Comment by pelumy** [comment]
@ceceliacreates, I would like to pick this up.

**Comment by ceceliacreates** [comment]
@pelumy assigned 🥳

**Comment by pelumy** [comment]
@clc80 and @devanshimodha, please review the wireframe when you have the time.

<img width="1330" alt="Screenshot 2024-03-05 at 10 16 32 am" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/54324355/f88d485c-69dc-4e39-a062-926b992f0908">

**Comment by ceceliacreates** [comment]
@pelumy This looks great, however I believe this is conflict with #239, which states that swiping left on a task will delete, not mark as done. I will let @clc80 and @devanshimodha decide if they prefer swiping left to delete or mark as done. 

If we decide to move forward with this approach, then I can close #239 as not planned.

**Comment by pelumy** [comment]
Ooh, noted @ceceliacreates, I meant to add it as an extra feature with the swipe to delete. But it is definitely fine to remove it.

I can remove it and attach a new wireframe screenshot
