### ISSUE TITLE
Android - UI - DetailScreen TextField

### ISSUE THREAD

**Issue by baghaii** [WomenWhoCode/WWCodeMobile#250]
## Add more details to describe what needs to be done. Include wireframes if applicable.
Currently, the TaskDetailScreen uses a TextField. However, an OutlinedTextField would be better here. 

To complete this ticket 
- change the TextField to an OutlinedTextField
- remove the colors being assigned on the text field
- remove the border being assigned in the modifier
- swap out the label text for a placeholder text

## If a PR already exists, link it to this issue
* See [how to manually link the pull request to the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)

## Get yourself assigned to this issue
* If you want to work on this issue, request to have it be assigned to you by:
1. Add a comment that you want to work on the issue
2. Tag a maintainer to request assignment

**Comment by Jacquigee** [comment]
@gaurigadkari @renweview Please assign this issue to me. Thanks

**Comment by baghaii** [comment]
I have assigned it to you, Jacqui!
