### ISSUE TITLE
iOS - Create wireframes for a done/complete button and a new screen to show completed tasks.

### ISSUE THREAD

**Issue by clc80** [WomenWhoCode/WWCodeMobile#260]
When a task is complete a user can press the done button. 
When the button is pressed the user will get a confirmation to make sure they intended to mark as complete. 
If the user says yes then the task will be taken off the main list and onto a separate done list.

**Comment by tsablon** [comment]
Hello @clc80 Inpick this issue

**Comment by tsablon** [comment]
Hello @clc80 @devanshimodha , Can you review this wireframe?

In this wireframe, we're assuming that the delete swiper from issue [#239](https://github.com/WomenWhoCode/WWCodeMobile/issues/239) is now available, allowing us to include a swiper with multiple actions here.

<img width="946" alt="Capture d’écran 2024-03-14 à 15 24 41" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/126064749/9db89d9c-b807-4d4c-b011-9df249aee1b8">

**Comment by clc80** [comment]
This is amazing. Great job.
