### ISSUE TITLE
iOS - UI - Fix Squished Textfield on Details View Screen

### ISSUE THREAD

**Issue by pelumy** [WomenWhoCode/WWCodeMobile#266]
Steps to reproduce:

- Tap on an activity to take you the details screen
- Make sure the software keyboard is toggled on if you are using a simulator
- Try to type in the textfield
- The textfield gets squished instead of other elements at the top of the screen being offset

Recording:
https://github.com/WomenWhoCode/WWCodeMobile/assets/54324355/49b744f8-fc8d-49a9-896b-9f6f5cde7560

**Comment by pelumy** [comment]
@clc80 and @devanshimodha, I would like to pick this up

**Comment by vuinguyen** [comment]
Fixed in PR https://github.com/WomenWhoCode/WWCodeMobile/pull/279
