### ISSUE TITLE
Android - Bug - Fix Date for New Tasks on Detail Screen

### ISSUE THREAD

**Issue by baghaii** [WomenWhoCode/WWCodeMobile#271]
## Add more details to describe what needs to be done. Include wireframes if applicable.
Currently, the date on the detail screen is wrong for people who do not live in UTC. That means that in the evenings (if you are in the US), if you try to add a new task, the date will be wrong. 

To fix this issue, remove the line in TimeUtil.kt that is setting the time zone to UTC.

## If a PR already exists, link it to this issue
* See [how to manually link the pull request to the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)

## Get yourself assigned to this issue
* If you want to work on this issue, request to have it be assigned to you by:
1. Add a comment that you want to work on the issue
2. Tag a maintainer to request assignment

**Comment by ThanaReka** [comment]
@baghaii I'd like to take on this issue.

**Comment by baghaii** [comment]
I assigned it to you @ThanaReka

**Comment by ThanaReka** [comment]
@baghaii, I'm not sure if I'm seeing the same error as mentioned in this issue.  The date seems to be set correctly when I try to enter a new task on the detail screen without making any changes to the TimeUtils.kt file.  But when I remove the mentioned line in this issue (formatter.timeZone = TimeZone.getTimeZone("UTC")), I am getting the previous date from the one I'm trying to pick in the date picker (I also checked the time zone on my emulator and found that it was set to Pacific Time).  Can you confirm that I am understanding this issue correctly, and whether you are still seeing the error as mentioned in this issue?

**Comment by baghaii** [comment]
I think this issue will show up after 5:00 PM in your time zone.

**Comment by ThanaReka** [comment]
Running the app on my emulator after 6 p.m. local time, and still seeing the same effect as before.

**Comment by baghaii** [comment]
Which time zone are you in? I thought you were in pacific time?

**Comment by baghaii** [comment]
It is now 6:47PM on March 25 in the Mountain Time Zone. 

Here is my details screen.

![Screenshot_1711414026](https://github.com/WomenWhoCode/WWCodeMobile/assets/7873908/f22be1e9-8205-4c0a-95b9-8bc13f875b0e)

**Comment by ThanaReka** [comment]
I see where the problem is.  Thanks for the clarification @baghaii!

**Comment by ThanaReka** [comment]
@baghaii, although my PR for this issue takes care of adding a new task according to the correct current date, I feel like it's going to cause problems if say, the user were to pick any other date.  After having removed the line in TimeUtil.kt that is setting the time zone to UTC, I see that the previous date always gets selected from the one I'm trying to pick in the date picker.  Let me know if you see this happening for you too!

**Comment by baghaii** [comment]
You are right! I think we should pass in a string for timezone, and it might take Locale.getDefault().toString() when it is called in the viewmodel, and it takes "UTC" when it is in the view.

**Comment by ThanaReka** [comment]
> You are right! I think we should pass in a string for timezone, and it might take Locale.getDefault().toString() when it is called in the viewmodel, and it takes "UTC" when it is in the view. 

This seems to resolve the impending issue.  Will commit the changes to my PR soon!
