### ISSUE TITLE
iOS - UI - Add a done/complete button

### ISSUE THREAD

**Issue by clc80** [WomenWhoCode/WWCodeMobile#272]
When a task is complete a user can press the done button.
When the button is pressed the user will get a confirmation to make sure they intended to mark as complete.
If the user says yes then the task will be taken off the main list and onto a separate done list.

<img width="600" alt="deleteWireframes" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/16246070/63a3b9ae-62be-40b6-b6cd-539a0762b5c0">

## Get yourself assigned to this issue
* If you want to work on this issue, request to have it be assigned to you by:
1. Add a comment that you want to work on the issue
2. Tag a maintainer to request assignment

**Comment by tsablon** [comment]
Hi @clc80, I'm thinking of choosing this task.
Should we wait for #274 to be finish first, or maybe bundle it with related issues in an Epic for easier management? There's many things to integrate so grouping them might help.

**Comment by clc80** [comment]
Sure if you think that would make it easier for you to implement.
