### ISSUE TITLE
Android - Bug - Fix task card on the Task List Screen

### ISSUE THREAD

**Issue by SttApollo** [WomenWhoCode/WWCodeMobile#284]
Add Maxlines to the text and clicking on the row will allow the users to see the entire text 

<img width="539" alt="Screenshot 2024-03-25 at 12 19 58 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/82180165/d648c091-4d47-4e58-bfc3-2092e16bd7ac">

**Comment by SttApollo** [comment]
@baghaii @gaurigadkari @renweview  - if you could assign this to me, thanks!

**Comment by renweview** [comment]
You are assigned! @SttApollo

**Comment by vuinguyen** [comment]
PR for this issue was merged. Will close issue now
