### ISSUE TITLE
Create a ReadMe Template with instructions for  all projects that has instructions, general good practices, Maintainer names, etc. 

### ISSUE THREAD

**Issue by clc80** [WomenWhoCode/WWCodeMobile#53]
Details can be taken from presentation

**Comment by vuinguyen** [comment]
Claudia, ping @gaurigadkari for review when you're ready. If you want a second review, ping @vuinguyen too

**Comment by vuinguyen** [comment]
Recordings and slides to the presentations are available here for reference:
https://github.com/WomenWhoCode/WWCodeMobile/tree/main/coding-projects/resources
