### ISSUE TITLE
Create App Wireframes for iOS and Android Projects

### ISSUE THREAD

**Issue by vuinguyen** [WomenWhoCode/WWCodeMobile#56]
create a set of wireframes for an MVP version of the iOS and Android projects. UI does not have to be pixel perfect or detailed by platform. Focus on high level components and app flow.

**Comment by vuinguyen** [comment]
Perhaps create wireframes for a simplified version of the [toggl app](https://toggl.com/track/mobile-time-tracking-app/), appropriate to present for an MVP at the Kick Off events in January.

**Comment by vuinguyen** [comment]
It seems toggl might be too complicated to model after for an MVP. How about if we look at the [timer feature of Clockify](https://clockify.me/features/timer)? For the MVP, I would look into implementing just the **one-click timer**, and the **add and edit time** features. 

I would leave out Categorize time, breaks, and Pomodoro out of the MVP for now. Those could go into future project extensions, depending on how long you all want to keep going. 

I think for the MVP, plan for features that the project can work on for 1-2 months at first after the Kick Off. Then see how it goes with contributors’ interest and your bandwidth, to determine additional months you want to do after that. What are your thoughts @gaurigadkari @renweview @devanshimodha ?

**Comment by renweview** [comment]
![timerapp wireframe1](https://github.com/WomenWhoCode/WWCodeMobile/assets/52512833/9d2edf85-569e-4854-9526-4d6dfb773545)
Frames dropped! I agree I think prioritizing the features are worth a discussion at our next meet.

**Comment by renweview** [comment]
Open to thoughts and happy to refresh this with new ideas.

**Comment by renweview** [comment]
![timerapp wireframe 2](https://github.com/WomenWhoCode/WWCodeMobile/assets/52512833/fe302935-9a97-4da9-8f2b-c954b2b9fdad)
![timerapp wireframe 3 ](https://github.com/WomenWhoCode/WWCodeMobile/assets/52512833/c7823b99-2309-4407-bf83-7a9b9e0fd005)

**Comment by vuinguyen** [comment]
These are great for an initial set of wireframes @renweview !

Here are some initial thoughts for feature prioritization:
For the MVP (a project you can work on for the first 1-2 months after kickoff), I would recommend building a CRUD app for _the time tracking portion only_ as a list or main-detail app.

For example:
**C** - **Create** - the user taps on the + button on the list or main screen, and takes them to the Create Timed Entry Screen. This is where the user can manually enter the time for their activity
**R** - **Read** - once the user creates the timed entry, it takes them back to the list (the main screen), which will now display the newly created entry as an item on the list
**U** - **Update** - tapping on an item on the list takes the user to a detail screen, with an edit button. Tapping on the edit button in the detail screen makes that screen editable. The Edit Screen can reuse the Create Timed Entry Screen.
**D** - **Delete** - Swipping left on a row in the list reveals a Delete button, which allows the user to delete that row in the list.

The calendar, settings, and maybe even user profile, could all go into the project extension phase. But those are my thoughts. Would like to know what you all think at the meeting!

**Comment by vuinguyen** [comment]
Here's something I quickly threw together on Excalidraw:

![CRUD Diagram of Time Tracking](https://github.com/WomenWhoCode/WWCodeMobile/assets/1022275/ead4c3cb-07d1-4a3c-a135-4554caf0201a)

**Comment by ceceliacreates** [comment]
Hey all! I'd like to help get started with creating GitHub issues. From the meeting notes, it sounds like the MVP should include:

**Screens for MVP:**

List screen - the screen that shows all the list of activities

Detail screen - when the user taps on an item from the list screen, the detail screen is launched with additional information for the particular activity

Manual timed entry - screen to add a new timed activity manually

**CRUD operations for activities**

Create a new timed activity - Manual timed entry 

Read, Update, Delete - List screen and Detail screen

If this is correct, I can break these down into GitHub issues for people to work on.

Also, are there wireframes ready for the List, Detail, and Manual Timed Entry screens?

**Comment by gaurigadkari** [comment]
> Hey all! I'd like to help get started with creating GitHub issues. From the meeting notes, it sounds like the MVP should include:
> 
> **Screens for MVP:**
> 
> List screen - the screen that shows all the list of activities
> 
> Detail screen - when the user taps on an item from the list screen, the detail screen is launched with additional information for the particular activity
> 
> Manual timed entry - screen to add a new timed activity manually
> 
> **CRUD operations for activities**
> 
> Create a new timed activity - Manual timed entry
> 
> Read, Update, Delete - List screen and Detail screen
> 
> If this is correct, I can break these down into GitHub issues for people to work on.
> 
> Also, are there wireframes ready for the List, Detail, and Manual Timed Entry screens?

@clc80 it would be good to break the requirements down as per your suggestion.
I think we can have 3 UI issues for each of the screens: 
List screen - the screen that shows all the list of activities
Detail screen - when the user taps on an item from the list screen, the detail screen is launched with additional information for the particular activity
Manual timed entry - screen to add a new timed activity manually
and 4 Business logic issues 1 for each of the CRUD operation (Create, Read, Update and Delete)
What are everyone's thoughts? @renweview @devanshimodha @vuinguyen

**Comment by vuinguyen** [comment]
> > Hey all! I'd like to help get started with creating GitHub issues. From the meeting notes, it sounds like the MVP should include:
> > **Screens for MVP:**
> > List screen - the screen that shows all the list of activities
> > Detail screen - when the user taps on an item from the list screen, the detail screen is launched with additional information for the particular activity
> > Manual timed entry - screen to add a new timed activity manually
> > **CRUD operations for activities**
> > Create a new timed activity - Manual timed entry
> > Read, Update, Delete - List screen and Detail screen
> > If this is correct, I can break these down into GitHub issues for people to work on.
> > Also, are there wireframes ready for the List, Detail, and Manual Timed Entry screens?
> 
> @ceceliacreates it would be good to break the requirements down as per your suggestion. I think we can have **3 UI issues for each of the screens:** List screen - the screen that shows all the list of activities Detail screen - when the user taps on an item from the list screen, the detail screen is launched with additional information for the particular activity Manual timed entry - screen to add a new timed activity manually and **4 Business logic issues 1 for each of the CRUD operations (Create, Read, Update and Delete)** What are everyone's thoughts? @renweview @devanshimodha @clc80 @vuinguyen

I wish there was a way to create threads in Github issues! I like your suggestions @ceceliacreates and @gaurigadkari .

I had an additional thought: Should the **Manual timed entry screen** be connected to both the **Create** and **Update** business logic issues? I think we can reuse that **Manual timed entry screen** for both operations, but it also depends on what the app wireframe for the Manual screen will look like. Something to consider also for @renweview in the wireframe creation 😊

**Comment by renweview** [comment]
Sounds good on all fronts, @vuinguyen and @gaurigadkari. Not too worried about the business logic until we make the manual timed entry screen frame-- I'm open to the logic becoming what makes sense to all of us. Thank you for rounding up the to-do's @ceceliacreates! We're working on this at today's meeting (1/10/24 9:30 PM ET).

**Comment by renweview** [comment]
![Screenshot 2024-01-10 223433](https://github.com/WomenWhoCode/WWCodeMobile/assets/52512833/730492b7-a39e-4a31-bcdc-b71c8746cebc)
Manual entry screen frame ✅ 
1/10/24 meeting notes updated on the Notion page.

**Comment by vuinguyen** [comment]
@renweview I think this is getting very close to what we want for the Edit / Add Entry Screen! Believe it or not, I think this can be simplified even further. What you have there is a count up timer. For the MVP, based on the planning meeting we had with @gaurigadkari , @devanshimodha , and myself, is that we want to create a timed entry **using date and time pickers** because they are less complicated to implement and test, instead of a count up timer.

Here's a couple of tutorials on Android date / time pickers, so you see what I'm talking about:
https://www.digitalocean.com/community/tutorials/android-date-time-picker-dialog
https://developer.android.com/develop/ui/views/components/pickers

FYI, there _are_ iOS date / time pickers, so these components will also work for iOS.

Here are a couple of tutorials on Android counting timers. I don't know if you can appreciate from these that it is more complicated. 
https://www.youtube.com/watch?v=7QVr5SgpVog
https://www.digitalocean.com/community/tutorials/android-countdowntimer-example
https://stackoverflow.com/questions/9276858/how-to-add-a-countup-timer-on-android

But my thoughts are maybe we can hold off on implementing counting timers, until phase 2 of the group project (after the MVP)?

**Comment by vuinguyen** [comment]
I saw the App Flows on the updated Miro board too @renweview ! The Add / Edit and Detail screens are looking good! I had a couple of questions that I sent to you over Slack for your consideration
