### ISSUE TITLE
Mind if I update the bookclub README? 

### ISSUE THREAD

**Issue by renweview** [WomenWhoCode/WWCodeMobile#60]
Heyo @vuinguyen mind if I add a small update to one of our old projects? On the Pragmatic Programmer series it looks like there was no update on why chapters 7-12 were not included and on the series ending. 
Could I add this: 
- Update: While this book club discussion group has ended as of December 2024, please join our Women Who Code Mobile Slack to stay updated on future events!

**Comment by vuinguyen** [comment]
@renweview I think updating the bookclub README with a quick note is a good idea. Although I would say the book club ended as of December **2023** (I'm getting ahead of myself too 😉). This is my fault for not following up with y'all on getting the notes for the rest of the chapters in. But let's worry about that in the new year. 

btw, you have maintainer permissions now so you should be able to submit a PR from this repo without creating a fork. Let me know if you have any questions about that. You can tag me for a review in your new PR. 

Gonna try to unplug later today and enjoy the long holiday break, so I may end up reviewing your PR in the new year, if that's alright. 😊
