### ISSUE TITLE
Android - Scaffold initial project structure

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#67]
Create the initial project in the `coding-projects/android` folder for contributors to fork.

**Comment by vuinguyen** [comment]
@gaurigadkari @renweview I've started reviewing the PR for the iOS initial project structure. You may want to look at my comments there to get an idea of some things to consider for your project structure: 
https://github.com/WomenWhoCode/WWCodeMobile/pull/81

**Comment by vuinguyen** [comment]
@gaurigadkari @renweview I just approved Claudia's latest PR, which looks good! 

You can also take a look at that for inspiration : https://github.com/WomenWhoCode/WWCodeMobile/pull/82
