### ISSUE TITLE
Android - UI - Detail/Add/Edit Screen (Epic)

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#69]
This is a parent task (epic) to track all issues related to the Detail/Add/Edit Screen. 

**This issue should not be assigned unless the same person is working on all 4 issues**

Close this issue once all dependencies are complete.

- [x] #88
- [x] #89
- [x] #90
- [x] #91
- [x] #92
- [x] #93
- [x] #94

<img width="273" alt="Screenshot 2024-01-24 at 5 30 44 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/cc3d38e0-3dde-4462-9d5e-284c1a6ad31c">

**Comment by vuinguyen** [comment]
All issues referenced in this epic have been completed. Will close this  epic now
