### ISSUE TITLE
Android - Logic - Add Timed Activity (Create)

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#73]
Add logic to app to allow user to add a new timed activity. This is associated with the Create operation.

- When viewing the Detail/Add/Edit screen in an "Add" context (triggered with tap of + button on List Screen)
- On tap of Done button, capture user input to create a new timed activity

Data associated with timed activity:

- activity name
- date
- start time
- end time
- duration
- id

<img width="860" alt="Screenshot 2024-01-24 at 5 58 34 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/3632a35f-ba8a-4623-8fea-bb3167ffee5e">

**Comment by renweview** [comment]
@SttApollo assigned via slack

**Comment by ceceliacreates** [comment]
@SttApollo can you please comment on this issue so it can be assigned to you? I can only assign if you comment. Thank you!

**Comment by SttApollo** [comment]
Hi! Please assign this to me

**Comment by ceceliacreates** [comment]
Hi @SttApollo is there progress on this issue? If not I will move to open so it can be reassigned, thank you.

**Comment by SttApollo** [comment]
@ceceliacreates Apologies, I haven't been able to get to this. I can definitely get to this on Monday - if that doesn't work yes please reassign.

**Comment by SttApollo** [comment]
@renweview  - you can reassign this to me if you like, once [PR 236](https://github.com/WomenWhoCode/WWCodeMobile/pull/236) is resolved! Apologies for the delay

**Comment by renweview** [comment]
@SttApollo how's it going with this one?

**Comment by SttApollo** [comment]
Hi @renweview , I'll have updates for you on this most likely tomorrow evening!

**Comment by baghaii** [comment]
Can you change the start and end times back to strings on the Tasks? I think I changed them earlier, and that was a bad call on my part. 

Hopefully, Luibov's PR that is out for review will be merged soon and that will let you wire up the last little bit to store things into the Task.

**Comment by SttApollo** [comment]
@baghaii could you please remind me why we want to change the start and end times back to String? I am also thinking of making duration a computed property so that we can just access it instead of having to calculate it in the views or the viewmodel. But if this approach isn't agreedable - lmk :)

**Comment by SttApollo** [comment]
@baghaii now that I am thinking more, the computed property might not he best solution if we were to allow user to update start and end time of an already created Task object. Are we allowing that?

**Comment by baghaii** [comment]
If you calculate these numbers yourself and treat the start of the day as time 0 and time can only go to 60 seconds * 60 minutes * 24 hours, then storing them as Ints is fine.

If you store them as milliseconds since the epoch and use the calendar calculations, those values are Longs, and I don't think that MySql will store them. 

My impression on duration was that perhaps it should always be calculated and never stored in the database. 

Where do we show duration? Is that what is on the main screen.

**Comment by SttApollo** [comment]
@baghaii I changed them back to Sring and didn't make duration as a computed property, I ended up just calculating it inside the TaskDetailView file.  

To my knowledge, it's shown on the TaskListScreen

https://github.com/WomenWhoCode/WWCodeMobile/pull/270
