### ISSUE TITLE
iOS - Logic -  Add Timed Activity (Create)

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#74]
Add logic to app to allow user to add a new timed activity. This is associated with the Create operation.

- When viewing the Detail/Add/Edit screen in an "Add" context (triggered with tap of + button on List Screen)
- On tap of Done button, capture user input to create a new timed activity

Data associated with timed activity:

- activity name
- date
- start time
- end time
- duration
- id

<img width="860" alt="Screenshot 2024-01-24 at 5 58 34 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/3632a35f-ba8a-4623-8fea-bb3167ffee5e">

**Comment by clc80** [comment]
@SttApollo Just checking in on this issue and making sure you were still interested and working on it.

**Comment by SttApollo** [comment]
@clc80  Hi I am! But it got really hectic unexpectedly- I'll be able to get to this over the weekend. If that's ok? The same goes for my other issues.

**Comment by clc80** [comment]
> @clc80 Hi I am! But it got really hectic unexpectedly- I'll be able to get to this over the weekend. If that's ok? The same goes for my other issues.


Yes, that is not a problem at all. Just wanted to make sure you were still working on it. I know life gets in the way sometimes.

**Comment by SttApollo** [comment]
@clc80 does the user have to add the End time here too or is that done somewhere else?

**Comment by clc80** [comment]
> @clc80 does the user have to add the End time here too or is that done somewhere else?

I don't see a separate issue for the endTime. We can add it to this one.
