### ISSUE TITLE
Android - Logic - Display Timed Activities (Read)

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#75]
Add logic to app that displays timed activities on the List Screen. This is associated with the Read operation. 

- List screen should display all existing timed activities on app open
- After any redirect to the List Screen from add, edit, or delete, the list should update to reflect change

<img width="458" alt="Screenshot 2024-01-24 at 5 03 11 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/bbe55dd4-86b9-4770-b624-5ebc2ef133a6">

**Comment by renweview** [comment]
@ThanaReka requested this issue

**Comment by ceceliacreates** [comment]
@ThanaReka can you please comment on this issue so it can be assigned? Thank you!

**Comment by ThanaReka** [comment]
@renweview @gaurigadkari!  I'd like to work on this issue, please.
