### ISSUE TITLE
iOS - Logic - Display Timed Activities (Read)

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#76]
Add logic to app that displays timed activities on the List Screen. This is associated with the Read operation. 

- List screen should display all existing timed activities on app open
- After any redirect to the List Screen from add, edit, or delete, the list should update to reflect change

<img width="458" alt="Screenshot 2024-01-24 at 5 03 11 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/bbe55dd4-86b9-4770-b624-5ebc2ef133a6">

**Comment by jancy123** [comment]
@clc80 @devanshimodha  would like to take this, but would need a bit more clarity. Do we need setup any db and from there we need to fetch the items?

**Comment by clc80** [comment]
@jancy123 I was talking with the rest of the team to get clarification on how we want to handle this for now. Eventually, we want to have SwiftData do the fetching of the items but for now, we may just do this in an array to make this simpler.

**Comment by clc80** [comment]
This issue was already implemented.
