### ISSUE TITLE
Android - Logic - Edit Timed Activity (Update)

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#77]
Add logic to the app that allows user to update existing timed activities. This is associated with the Update operation.

- When tapping the Done button the Detail/Add/Edit screen in the "Edit" context (triggered by selecting an existing timed entry)
- Existing entry should update with changes based on user input

<img width="865" alt="Screenshot 2024-01-24 at 6 12 09 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/cbd73c42-251a-4e4c-a712-309c46c585ec">

**Comment by jyoshna-joshi** [comment]
Hi, @renweview  and @gaurigadkari, I woulld like to work on this issue please.

**Comment by renweview** [comment]
You got it @jyoshna-joshi

**Comment by jyoshna-joshi** [comment]
@renweview @gaurigadkari  Should I wait for the completion of issues #84 (List Screen) and #73 (Add logic) before beginning work on this issue?

**Comment by renweview** [comment]
@jyoshna-joshi did you get a response to your question on Slack? I believe we said it's still possible to continue forward on this one, looping @gaurigadkari to confirm

**Comment by jyoshna-joshi** [comment]
@renweview Yes, I am working on it and will submit PR once it is finished.

**Comment by jyoshna-joshi** [comment]
Hi, I've completed the logic aspect, but I implemented it using a random button click. I am integrating it into the task detail screen on  "Done" button click. I will remove unnecessary code and will submit PR then. Thanks

**Comment by renweview** [comment]
@jyoshna-joshi how's it going on this?

**Comment by jyoshna-joshi** [comment]
Hey. I'm currently in the process of implementing this using Hilt for dependency injection, which is taking some time. Should I persist with using Hilt for this purpose or should avoid using it?

**Comment by renweview** [comment]
Open to thoughts @gaurigadkari @baghaii previously on related questions like this, I believe it was ok to try it out @jyoshna-joshi and we'd discuss after we see the code

**Comment by jyoshna-joshi** [comment]
Yes, we need ROOM database and we don't have set up for it. I have created ROOM database to work on this task. However, if someone is working on add logic, it may create conflict.
