### ISSUE TITLE
iOS - Logic - Edit Timed Activity (Update)

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#78]
Add logic to the app that allows user to update existing timed activities. This is associated with the Update operation.

- When tapping the Done button the Detail/Add/Edit screen in the "Edit" context (triggered by selecting an existing timed entry)
- Existing entry should update with changes based on user input

<img width="865" alt="Screenshot 2024-01-24 at 6 12 09 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/cbd73c42-251a-4e4c-a712-309c46c585ec">

**Comment by lulu-cao** [comment]
@devanshimodha @clc80 Could I grab this issue please?
