### ISSUE TITLE
Android - Logic - Delete Timed Activity

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#79]
Add logic to app to delete timed activities.

- When tapping the "ok" option on the delete confirmation popup
- Existing entry should be deleted

<img width="865" alt="Screenshot 2024-01-24 at 6 13 22 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/8365d594-7a07-4d9c-83ac-df9b33fe1d0d">

**Comment by renweview** [comment]
@lsireneva requested to be assigned to this issue via slack

**Comment by ceceliacreates** [comment]
@lsireneva can you please comment on this issue so it can be assigned? This is required by GitHub to assign the issue to you and is part of the process. Thank you!

**Comment by lsireneva** [comment]
Please assign this issue on me

**Comment by renweview** [comment]
since #203 dealt with this, I will close this issue

**Comment by renweview** [comment]
@lsireneva since this is entangled with #203 are you able to tackle this one next instead of #90 next? To clear the misunderstanding up

**Comment by renweview** [comment]
unblocked this issue since #203 was closed

**Comment by ThanaReka** [comment]
> unblocked this issue since #203 was closed
> 
> 

Hi @renweview!  I would like to this issue if it's available.

**Comment by baghaii** [comment]
This has been re-assigned to @lsireneva because it is related to her work and because @ThanaReka is assigned another really high priority ticket that is not blocked.
