### ISSUE TITLE
Android - UI - List Screen: Scaffold initial screen with headers, + button, and list container

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#84]
- Create a list screen
- Add headers
- Add + button
- Add container for list items

<img width="458" alt="Screenshot 2024-01-24 at 5 03 11 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/f49b0ff9-cacb-47d1-9ce4-8bda07afef2b">

**Comment by ThanaReka** [comment]
Hi, I would like to work on this issue if it's available.  (Reka Thanabalan)

**Comment by ThanaReka** [comment]
Hi @renweview @gaurigadkari.  I wanted to clarify whether the "Timer" title of the screen and the add button were meant to be part of the TopAppBar or not. Thanks!

**Comment by renweview** [comment]
Heyo @ThanaReka! It certainly can go there, what do you think @gaurigadkari? Example: https://foso.github.io/Jetpack-Compose-Playground/material/topappbar/

**Comment by gaurigadkari** [comment]
> Heyo @ThanaReka! It certainly can go there, what do you think @gaurigadkari? Example: https://foso.github.io/Jetpack-Compose-Playground/material/topappbar/

+1 @ThanaReka if you think having an issue to have a common TopAppBar for the entire app, which can be customised like title change and icons can be different, go ahead and create that issue
