### ISSUE TITLE
Android - UI - List Screen: Add list items that show activity name and time of activity

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#85]
- Add list items
- Display activity name for each item
- Display time duration of activity for each item
- List should scroll

<img width="458" alt="Screenshot 2024-01-24 at 5 03 11 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/0a43e2d8-aa8e-4e58-931d-5af5525b39e1">

**Comment by jyoshna-joshi** [comment]
Hi, is this issue available? I would like to do it once it is unblocked. Thanks

**Comment by ceceliacreates** [comment]
Hi @jyoshna-joshi, this issue is no longer blocked. I will go ahead and assign it to you now to work on once #77 is complete.

**Comment by renweview** [comment]
This issue is being reworked internally @ceceliacreates so we shouldn't assign just yet. Apologies @jyoshna-joshi

**Comment by ceceliacreates** [comment]
@renweview what is required to unblock this issue so it can be assigned?

**Comment by renweview** [comment]
A lot of the tasks here have been completed in https://github.com/WomenWhoCode/WWCodeMobile/issues/84
so we can check the code to see what's left over and edit this issue accordingly + ask the user for #84 to refactor

**Comment by ceceliacreates** [comment]
Thanks for the context. Based on the code, it looks like all the UI is completed for this issue with hardcoded values, so I will go ahead and close this.
