### ISSUE TITLE
Android - UI - List Screen: Link + button to Detail/Add/Edit screen

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#87]
Link + button to Detail/Add/Edit screen

<img width="458" alt="Screenshot 2024-01-24 at 5 03 11 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/76808f99-c5a6-4bc0-9376-96f845f454fa">

**Comment by cyndichin** [comment]
@renweview @gaurigadkari I would like to work when its unblocked! thanks! :)

**Comment by ceceliacreates** [comment]
Hi @cyndichin, this issue is unblocked, however you already have another open issue claimed #171 so I can assign this one once 171 is complete. Thanks!

**Comment by lsireneva** [comment]
@ceceliacreates I did changes for this part. Is okay if you assign issue on me?

**Comment by gaurigadkari** [comment]
> @ceceliacreates I did changes for this part. Is okay if you assign issue on me?

@lsireneva as you see from @ceceliacreates' comment above, we are having people wrap up an issue before picking another one up. Can you try to have separate PRs for separate issues, and work on things only after they have been assigned to you to avoid work being duplicated.

**Comment by ceceliacreates** [comment]
Hi @lsireneva I assigned this issue to you based on the conversation in Slack.

**Comment by lsireneva** [comment]
@ceceliacreates Hi Cecelia, I think we can close this issue, my PR was merged to main.

**Comment by renweview** [comment]
@lsireneva closed since it was done in #220! Thank you
