### ISSUE TITLE
Android - UI - Detail Screen: Scaffold initial screen with elements

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#88]
- Create Detail/Add/Edit screen
- Add Date, Start time, and End time text
- Add textbox for activity description
- Add button that displays date
- Add button that displays start time
- Add button that displays end time
- Add delete button
- Add cancel button
- Add done button

<img width="273" alt="Screenshot 2024-01-24 at 5 30 44 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/56d8fd68-1f15-4fa6-8d23-d5a73afb30ba">

**Comment by lsireneva** [comment]
Hi, I would like to work on this screen (Liubov Sireneva)

**Comment by lsireneva** [comment]
@ceceliacreates Hi Cecelia, my PR was merged, I think we can close this issue and unblock related?

**Comment by renweview** [comment]
@lsireneva I think you're right! I'd refer to this on the next task since there's a few more: https://github.com/WomenWhoCode/WWCodeMobile/issues/69 

looping @vuinguyen if we're ok to close from here

**Comment by vuinguyen** [comment]
@renweview yes, I think it's okay to close from here. Let's please loop @gaurigadkari into this as well, as the lead Android maintainer, to plan the next tasks!
