### ISSUE TITLE
Android - UI - Detail Screen: Add date picker

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#89]
- on tap of date button, launch date picker popup
- add date picker with cancel and ok options
- on tap of ok option, dismiss popup and display selected date on button
- on tap of cancel option, dismiss popup

<img width="727" alt="Screenshot 2024-01-24 at 5 40 51 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/63e79ac1-9c4c-46d8-99c1-2b0980f46d6d">

**Comment by lsireneva** [comment]
I can work on it

**Comment by renweview** [comment]
@lsireneva you got it

**Comment by lsireneva** [comment]
> @lsireneva do you still want this issue?

Yes, please :)

**Comment by renweview** [comment]
You got it! @lsireneva

**Comment by ceceliacreates** [comment]
@lsireneva I don't see a PR associated with this issue, can you confirm you are working on it? If not I will mark it as open so it can be reassigned. Thank you.

**Comment by lsireneva** [comment]
> @lsireneva I don't see a PR associated with this issue, can you confirm you are working on it? If not I will mark it as open so it can be reassigned. Thank you.

Yes, I did changes. I will create PR today
