### ISSUE TITLE
Android - UI - Detail Screen: Add time pickers

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#90]
- On tap of start and end time buttons, launch time picker popup
- Display time picker with cancel and ok options
- On tap of ok option, dismiss popup and show updated time on corresponding button
- On tap of cancel option, dismiss popup

<img width="727" alt="Screenshot 2024-01-24 at 5 40 51 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/f6526d45-2460-4968-80cf-a5755d8c085f">

**Comment by lsireneva** [comment]
I can work on it

**Comment by renweview** [comment]
Issue is open for contributions

**Comment by ceceliacreates** [comment]
Hi @lsireneva this issue is now unblocked however you have two other claimed issues #89 and #79 so please complete those first before I can assign this one. Thanks!

**Comment by lsireneva** [comment]
@ceceliacreates Hi Cecilia, can I work on this issue? I finished with other issues. One that I have is blocked.

**Comment by ceceliacreates** [comment]
@lsireneva assigned!

**Comment by vuinguyen** [comment]
@baghaii Since the PR for this issue has been merged, I'll go ahead and close this issue for you, if that's alright
