### ISSUE TITLE
Android - UI - Detail Screen: Add confirmation popup for cancel button

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#91]
- on tap of cancel button, launch confirmation popup with ok and cancel options
- on tap of cancel option on popup, dismiss popup
- on tap of ok option, redirect back to List Screen

<img width="545" alt="Screenshot 2024-01-24 at 5 46 00 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/48cafa8e-dc3c-471d-b5e7-63d4173c06ab">

**Comment by Shradhajoshi** [comment]
Hi, I would like to work on this.

**Comment by ceceliacreates** [comment]
Hi @Shradhajoshi this issue is now unblocked, I have assigned you. Thanks!
