### ISSUE TITLE
Android - UI - Detail Screen: Add confirmation popup for delete button

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#92]
- on tap of delete button, launch confirmation popup with ok and cancel options
- on tap of cancel option on popup, dismiss popup
- on tap of ok option, redirect back to List Screen

<img width="545" alt="Screenshot 2024-01-24 at 5 46 08 PM" src="https://github.com/WomenWhoCode/WWCodeMobile/assets/40367173/452c7b36-e729-448d-a5a1-30faddbc3cdb">

**Comment by Shradhajoshi** [comment]
Hi, I would like to work on this.

**Comment by ceceliacreates** [comment]
Hi @Shradhajoshi I can assign you this issue once your other issue #91 is complete. Thanks!

**Comment by lsireneva** [comment]
@ceceliacreates Please excuse me I implemented changes for this one in my issue

**Comment by ceceliacreates** [comment]
@lsireneva please only complete one PR per issue. Which PR is associated with this issue?

**Comment by ceceliacreates** [comment]
Hi @lsireneva is the work for this issue complete? If so, can you please let me know which PR? Thank you!

**Comment by renweview** [comment]
@ceceliacreates if no response by today, maybe we can call it an open issue and I'll post it on slack to promote

**Comment by lsireneva** [comment]
@ceceliacreates @renweview Hi, we need open this issue. Changes was not done, I waiting for database changes

**Comment by renweview** [comment]
@lsireneva any update on this?

**Comment by renweview** [comment]
We've passed the reply time on this so it's open for anyone

**Comment by lsireneva** [comment]
@renweview Could you please assign this on me?

**Comment by renweview** [comment]
@lsireneva how's it going on this one! 🙌

**Comment by lsireneva** [comment]
> @lsireneva how's it going on this one! 🙌

Hi Ren, I plan open PR today.
