### ISSUE TITLE
Android - Data - Add in-app persistence

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#95]
Add in-app persistence to store changes to the timed activities.

**Comment by SttApollo** [comment]
@renweview @gaurigadkari I would like to work on this if I can get more details on this issue - are we looking to use Rooms, Shared Preferences or something else here?

**Comment by gaurigadkari** [comment]
> @renweview @gaurigadkari I would like to work on this if I can get more details on this issue - are we looking to use Rooms, Shared Preferences or something else here?

@SttApollo if you think we need a new issue to spike if we need room or shared pref you can create that

**Comment by gaurigadkari** [comment]
@SttApollo do you want to pick this one up?

**Comment by SttApollo** [comment]
@gaurigadkari  yes please assign it to me and I'll also create new issues related to this

**Comment by ceceliacreates** [comment]
Hi @SttApollo is there any progress on this issue? If not I will mark as open so it can be reassigned.

**Comment by SttApollo** [comment]
@ceceliacreates  Apologies i haven't been able to get to this. I can definitely get to this on Monday - if that doesn't work yes please reassign.

**Comment by vuinguyen** [comment]
@gaurigadkari I think it would help to give @SttApollo some more guidance on this issue. Does the Android team want to use Room? FYI, the iOS team has went with SwiftData, which is the database for SwiftUI. So maybe the Android team wants to use Room with Compose, for similar implementation / feature parity with iOS? What do you think?

I found [this tutorial on Room](https://developer.android.com/codelabs/basic-android-kotlin-compose-persisting-data-room#0) if it helps @SttApollo with planning / breaking up this issue

**Comment by SttApollo** [comment]
thank you @vuinguyen - looks like we are going with Rooms, I now see that @gaurigadkari  added a template for Rooms. I am working on this now
